apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: fin-pfe-templatesv2
  description: Fin Platform Engineering Templates
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  targets:
    - ./fin-pfe-web-stack/template.yaml
